repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.10.4
    hooks:
      - id: validate_manifest

  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        exclude: ^(docs/|tests/).*$
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
      - id: pylint
        additional_dependencies: ["isort[pyproject]"]
        exclude: ^(docs/|tests/).*$
        # disabled import-error as may be run out of environment with deps
        args: ["--disable=import-error"]
